'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17379
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class LocalizedResources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DriveWorksLabs.SolidWorksWorkgroupPdm.LocalizedResources", GetType(LocalizedResources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to DriveWorks.
    '''</summary>
    Friend Shared ReadOnly Property CheckInComment() As String
        Get
            Return ResourceManager.GetString("CheckInComment", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The environment variable {0} already exists.
    '''</summary>
    Friend Shared ReadOnly Property EnvironmentVariableExists() As String
        Get
            Return ResourceManager.GetString("EnvironmentVariableExists", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The environment variable {0} has been removed.
    '''</summary>
    Friend Shared ReadOnly Property EnvironmentVariableRemoved() As String
        Get
            Return ResourceManager.GetString("EnvironmentVariableRemoved", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The environment variable {0} has been inserted.
    '''</summary>
    Friend Shared ReadOnly Property EnvironmentVariableSet() As String
        Get
            Return ResourceManager.GetString("EnvironmentVariableSet", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Environment Variable.
    '''</summary>
    Friend Shared ReadOnly Property EnvironmentVariableTitle() As String
        Get
            Return ResourceManager.GetString("EnvironmentVariableTitle", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to About to create project  &apos;{0}&apos; in parent &apos;{1}&apos;.
    '''</summary>
    Friend Shared ReadOnly Property LogDescAboutToAddProjectToParent() As String
        Get
            Return ResourceManager.GetString("LogDescAboutToAddProjectToParent", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to About to check in file &apos;{0}&apos;.
    '''</summary>
    Friend Shared ReadOnly Property LogDescAboutToCheckInFile() As String
        Get
            Return ResourceManager.GetString("LogDescAboutToCheckInFile", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to About to create project structure &apos;{0}&apos;.
    '''</summary>
    Friend Shared ReadOnly Property LogDescAboutToCreateProjectStructure() As String
        Get
            Return ResourceManager.GetString("LogDescAboutToCreateProjectStructure", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Queuing folder &apos;{0}&apos; for addition at the end of the batch..
    '''</summary>
    Friend Shared ReadOnly Property LogDescAboutToQueueFolder() As String
        Get
            Return ResourceManager.GetString("LogDescAboutToQueueFolder", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Adding file &apos;{0}&apos; threw an unexpected exception. {1}.
    '''</summary>
    Friend Shared ReadOnly Property LogDescAddFileEx() As String
        Get
            Return ResourceManager.GetString("LogDescAddFileEx", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Adding folder &apos;{0}&apos; threw an unexpected exception. {1}.
    '''</summary>
    Friend Shared ReadOnly Property LogDescAddFolderEx() As String
        Get
            Return ResourceManager.GetString("LogDescAddFolderEx", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Adding folder &apos;{0}&apos; returned {1}..
    '''</summary>
    Friend Shared ReadOnly Property LogDescAddFolderResult() As String
        Get
            Return ResourceManager.GetString("LogDescAddFolderResult", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Begin Batch aborted because no vault name is specified..
    '''</summary>
    Friend Shared ReadOnly Property LogDescBeginBatchAborted() As String
        Get
            Return ResourceManager.GetString("LogDescBeginBatchAborted", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Begin Batch incremented batch depth to {0}.
    '''</summary>
    Friend Shared ReadOnly Property LogDescBeginBatchIncrement() As String
        Get
            Return ResourceManager.GetString("LogDescBeginBatchIncrement", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Project &apos;{0}&apos; cannot be added as its parent ({1}) cannot be found.
    '''</summary>
    Friend Shared ReadOnly Property LogDescCannotFindParent() As String
        Get
            Return ResourceManager.GetString("LogDescCannotFindParent", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The directory &apos;{0}&apos; could not be added to the vault with the path &apos;{1}&apos; because one or more of the projects on the path could not be found and could not be created..
    '''</summary>
    Friend Shared ReadOnly Property LogDescCheckingInDirIntoProjectFailedEnsureFailed() As String
        Get
            Return ResourceManager.GetString("LogDescCheckingInDirIntoProjectFailedEnsureFailed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The file &apos;{0}&apos; is about to be checked into the project &apos;{1}&apos;.
    '''</summary>
    Friend Shared ReadOnly Property LogDescCheckingInFileIntoProject() As String
        Get
            Return ResourceManager.GetString("LogDescCheckingInFileIntoProject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The file &apos;{0}&apos; checkin failed into project &apos;{1}&apos;.
    '''</summary>
    Friend Shared ReadOnly Property LogDescCheckingInFileIntoProjectFailed() As String
        Get
            Return ResourceManager.GetString("LogDescCheckingInFileIntoProjectFailed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The file &apos;{0}&apos; could not be checked into the vault with the path &apos;{1}&apos; because one or more of the parent projects could not be found and could not be created..
    '''</summary>
    Friend Shared ReadOnly Property LogDescCheckingInFileIntoProjectFailedEnsureFailed() As String
        Get
            Return ResourceManager.GetString("LogDescCheckingInFileIntoProjectFailedEnsureFailed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The file &apos;{0}&apos; was successfully check in into project &apos;{1}&apos; and was created with the name &apos;{2}&apos;.
    '''</summary>
    Friend Shared ReadOnly Property LogDescCheckingInFileIntoProjectSuccess() As String
        Get
            Return ResourceManager.GetString("LogDescCheckingInFileIntoProjectSuccess", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to End Batch aborted because no vault name is specified..
    '''</summary>
    Friend Shared ReadOnly Property LogDescEndBatchAborted() As String
        Get
            Return ResourceManager.GetString("LogDescEndBatchAborted", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to End Batch aborted because the batch depth is already 0..
    '''</summary>
    Friend Shared ReadOnly Property LogDescEndBatchAborted_AlreadyZero() As String
        Get
            Return ResourceManager.GetString("LogDescEndBatchAborted_AlreadyZero", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to End Batch decremented the batch depth to {0}..
    '''</summary>
    Friend Shared ReadOnly Property LogDescEndBatchDecrement() As String
        Get
            Return ResourceManager.GetString("LogDescEndBatchDecrement", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The file &apos;{0}&apos; was successfully added.
    '''</summary>
    Friend Shared ReadOnly Property LogDescFileAdded() As String
        Get
            Return ResourceManager.GetString("LogDescFileAdded", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The file &apos;{0}&apos; was successfully checked in.
    '''</summary>
    Friend Shared ReadOnly Property LogDescFileCheckedIn() As String
        Get
            Return ResourceManager.GetString("LogDescFileCheckedIn", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Queuing file &apos;{0}&apos; to the assembly list..
    '''</summary>
    Friend Shared ReadOnly Property LogDescFileQueued_Assemblies() As String
        Get
            Return ResourceManager.GetString("LogDescFileQueued_Assemblies", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Queuing file &apos;{0}&apos; to the drawing list..
    '''</summary>
    Friend Shared ReadOnly Property LogDescFileQueued_Drawings() As String
        Get
            Return ResourceManager.GetString("LogDescFileQueued_Drawings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Queuing file &apos;{0}&apos; to the general list..
    '''</summary>
    Friend Shared ReadOnly Property LogDescFileQueued_General() As String
        Get
            Return ResourceManager.GetString("LogDescFileQueued_General", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Queuing file &apos;{0}&apos; to the parts list..
    '''</summary>
    Friend Shared ReadOnly Property LogDescFileQueued_Parts() As String
        Get
            Return ResourceManager.GetString("LogDescFileQueued_Parts", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The file &apos;{0}&apos; has a relative path of &apos;{1}&apos;.
    '''</summary>
    Friend Shared ReadOnly Property LogDescFileRelativePath() As String
        Get
            Return ResourceManager.GetString("LogDescFileRelativePath", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Project &apos;{0}&apos; has been created as a child of &apos;{1}&apos;.
    '''</summary>
    Friend Shared ReadOnly Property LogDescProjectAddedToParent() As String
        Get
            Return ResourceManager.GetString("LogDescProjectAddedToParent", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The project &apos;{0}&apos; already exists in the vault and is the root project.
    '''</summary>
    Friend Shared ReadOnly Property LogDescProjectAlreadyInVaultAndIsRoot() As String
        Get
            Return ResourceManager.GetString("LogDescProjectAlreadyInVaultAndIsRoot", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The project &apos;{0}&apos; already exists in the vault with parent &apos;{1}&apos;.
    '''</summary>
    Friend Shared ReadOnly Property LogDescProjectAlreadyInVaultWithParent() As String
        Get
            Return ResourceManager.GetString("LogDescProjectAlreadyInVaultWithParent", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unable to create the project &apos;{0}&apos; in parent &apos;{1}&apos;. {2}.
    '''</summary>
    Friend Shared ReadOnly Property LogDescProjectCreationFailed() As String
        Get
            Return ResourceManager.GetString("LogDescProjectCreationFailed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unable to create the project &apos;{0}&apos; as there is no connection to the vault available.
    '''</summary>
    Friend Shared ReadOnly Property LogDescProjectCreationFailedCompletelyNoVault() As String
        Get
            Return ResourceManager.GetString("LogDescProjectCreationFailedCompletelyNoVault", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Queuing file &apos;{0}&apos; was aborted because no vault name was specified..
    '''</summary>
    Friend Shared ReadOnly Property LogDescQueueFileAborted() As String
        Get
            Return ResourceManager.GetString("LogDescQueueFileAborted", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Queuing file &apos;{0}&apos; was aborted because the file was not underneath the Default Specification Folder..
    '''</summary>
    Friend Shared ReadOnly Property LogDescQueueFileAbortedNotInVault() As String
        Get
            Return ResourceManager.GetString("LogDescQueueFileAbortedNotInVault", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Queuing folder &apos;{0}&apos; was aborted because no vault name was specified..
    '''</summary>
    Friend Shared ReadOnly Property LogDescQueueFolderAborted() As String
        Get
            Return ResourceManager.GetString("LogDescQueueFolderAborted", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Queuing folder &apos;{0}&apos; was aborted because the folder was not underneath the Default Specification Folder..
    '''</summary>
    Friend Shared ReadOnly Property LogDescQueueFolderAbortedNotInVault() As String
        Get
            Return ResourceManager.GetString("LogDescQueueFolderAbortedNotInVault", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The Default Specification Folder, which will be considered the root of the vault, is &apos;{0}&apos;.
    '''</summary>
    Friend Shared ReadOnly Property LogDescVaultRootPath() As String
        Get
            Return ResourceManager.GetString("LogDescVaultRootPath", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unable to connect to the WorkgroupPDM interface, check that WorkgroupPDM is available and of the correct version..
    '''</summary>
    Friend Shared ReadOnly Property LogPDMCannotCreateInterface() As String
        Get
            Return ResourceManager.GetString("LogPDMCannotCreateInterface", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Vault Name.
    '''</summary>
    Friend Shared ReadOnly Property LogSettingNameVaultName() As String
        Get
            Return ResourceManager.GetString("LogSettingNameVaultName", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Vault User Name.
    '''</summary>
    Friend Shared ReadOnly Property LogSettingNameVaultUserName() As String
        Get
            Return ResourceManager.GetString("LogSettingNameVaultUserName", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Add File.
    '''</summary>
    Friend Shared ReadOnly Property LogTitleAddFile() As String
        Get
            Return ResourceManager.GetString("LogTitleAddFile", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Add Folder.
    '''</summary>
    Friend Shared ReadOnly Property LogTitleAddFolder() As String
        Get
            Return ResourceManager.GetString("LogTitleAddFolder", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Batch.
    '''</summary>
    Friend Shared ReadOnly Property LogTitleBatch() As String
        Get
            Return ResourceManager.GetString("LogTitleBatch", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Check In.
    '''</summary>
    Friend Shared ReadOnly Property LogTitleCheckIn() As String
        Get
            Return ResourceManager.GetString("LogTitleCheckIn", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Load Settings.
    '''</summary>
    Friend Shared ReadOnly Property LogTitleLoadSettings() As String
        Get
            Return ResourceManager.GetString("LogTitleLoadSettings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Setting &apos;{0}&apos; was loaded, its value is &apos;{1}&apos;.
    '''</summary>
    Friend Shared ReadOnly Property LogTitleSettingLoaded() As String
        Get
            Return ResourceManager.GetString("LogTitleSettingLoaded", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Vault Root Path.
    '''</summary>
    Friend Shared ReadOnly Property LogTitleVaultRootPath() As String
        Get
            Return ResourceManager.GetString("LogTitleVaultRootPath", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Attempt 1 - Unable to login to WorkgroupPDM with the details supplied. Trying again with default ports - {0}.
    '''</summary>
    Friend Shared ReadOnly Property LogVaultLoginAttempt1Failed() As String
        Get
            Return ResourceManager.GetString("LogVaultLoginAttempt1Failed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Attempt 2 - Unable to login to WorkgroupPDM with the default ports - {0}.
    '''</summary>
    Friend Shared ReadOnly Property LogVaultLoginAttempt2Failed() As String
        Get
            Return ResourceManager.GetString("LogVaultLoginAttempt2Failed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unable to login to Workgroup PDM with the details supplied (Error code {0}).
    '''</summary>
    Friend Shared ReadOnly Property LogvaultLoginNonZeroErrorCode() As String
        Get
            Return ResourceManager.GetString("LogvaultLoginNonZeroErrorCode", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SolidWorks Workgroup PDM integration for DriveWorks.
    '''</summary>
    Friend Shared ReadOnly Property PluginDescription() As String
        Get
            Return ResourceManager.GetString("PluginDescription", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SolidWorks Workgroup PDM.
    '''</summary>
    Friend Shared ReadOnly Property PluginName() As String
        Get
            Return ResourceManager.GetString("PluginName", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SolidWorks Workgroup PDM.
    '''</summary>
    Friend Shared ReadOnly Property SourceTitle() As String
        Get
            Return ResourceManager.GetString("SourceTitle", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The connection to the SolidWorks Workgroup PDM vault was unsuccessful. {0}.
    '''</summary>
    Friend Shared ReadOnly Property TestFailed() As String
        Get
            Return ResourceManager.GetString("TestFailed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The connection to the SolidWorks Workgroup PDM vault was successful..
    '''</summary>
    Friend Shared ReadOnly Property TestSucceeded() As String
        Get
            Return ResourceManager.GetString("TestSucceeded", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Connection Test.
    '''</summary>
    Friend Shared ReadOnly Property TestTitle() As String
        Get
            Return ResourceManager.GetString("TestTitle", resourceCulture)
        End Get
    End Property
End Class
